### ISSUE TITLE
Cannot run on Ventura 13.3.1

### ISSUE THREAD

**Issue by revans23** [lxy1992/mac-network-switch#6] opened 2023-04-24 21:53 UTC
I was unable to run this package, I am sure it is something simple - I'm very much a terminal noob.

I didn't have go installed so I used Brew to install it:
`brew install go`

Then I installed the package:
`go install github.com/lxy1992/mac-network-switch@latest`

`go: downloading github.com/lxy1992/mac-network-switch v0.0.2`
`go: downloading github.com/spf13/cobra v1.6.1`
`go: downloading github.com/spf13/pflag v1.0.5`

Then I received errors when trying to run it:
`sudo mac-network-switch toggleAirport --switch start`
`sudo: mac-network-switch: command not found`

`sudo go run mac-network-switch toggleAirport --switch start `
`package mac-network-switch is not in GOROOT (/opt/homebrew/Cellar/go/1.20.3/libexec/src/mac-network-switch)`

`sudo go run /opt/homebrew/Cellar/go/1.20.3/libexec/src/mac-network-switch toggleAirport --switch start`
`go: go.mod file not found in current directory or any parent directory; see 'go help modules'`

Please help!

TIA

**Comment by lxy1992** [comment] 2023-04-25 12:20
I haven't seen this problem before, but let't try to fix it. It seems like the installed binary is not in your system's PATH. To fix this issue, you can follow these steps:

1. Check if the binary is installed in your `$GOPATH`. By default, the `$GOPATH` should be `~/go`. If you haven't set a custom `$GOPATH`, the binary should be located at `~/go/bin/mac-network-switch`.

2. Add the `$GOPATH/bin` directory to your system's PATH. To do this, open the Terminal and run:

```bash
echo 'export PATH=$PATH:~/go/bin' >> ~/.zshrc
```

If you are using Bash instead of Zsh, replace `~/.zshrc` with `~/.bashrc`.

3. Restart the Terminal or run `source ~/.zshrc` (or `source ~/.bashrc` if you're using Bash) to apply the changes to the current session.

4. Now you should be able to run the command:

```bash
sudo mac-network-switch toggleAirport --switch start
```

If it still doesn't work, ensure that the `mac-network-switch` binary exists in the `~/go/bin` directory. If it's not there, you can try reinstalling the package with `go install`. If the issue persists, consider checking your `$GOPATH` and `$GOBIN` environment variables to ensure they are set correctly.

If it still cannot work, please send me the error message in this thread.

**Comment by lxy1992** [comment] 2023-04-25 12:24
My OS version is the same as yours, so I believe this tool should work if we run it in a right way.

**Comment by revans23** [comment] 2023-04-25 15:04
Ok - it did successfully run!  However, wifi maintains connection when I plug in my USB-C hub which contains the NIC.

**Comment by lxy1992** [comment] 2023-04-26 06:31
What is the name of your cable network connection? You can find the name in the Preference-Network, if it's not the "USB 10/100/1000 LAN", please tell me, it may require a change in the code. If the name of network is right, please try to turn on and off once, then check again.

PS: Because the WIFI would only closed after the cable network connected successfully (then system changes the network config file), so it usually takes about 30 seconds after you plugin in the cable network.

**Comment by revans23** [comment] 2023-04-27 20:15
It is AX88179A


Rich Evans
he/him/his

Mobile: 704-562-6652
***@***.*** ***@***.***>

**Comment by lxy1992** [comment] 2023-05-06 08:38
I see, it seems you are using a USB 3.1 Gen1 Bus to connect the RJ45 port, this repo is for USB 3.1 Gen2 Bus, I can add support for it, but I have no device to test it. You may have to be the first user of it, I will let you know when I add the support.

**Comment by lxy1992** [comment] 2023-05-06 09:09
@revans23 
I have add the support for your USB version, you could try it, just reinstall this tool at version 0.0.3,
```
go install github.com/lxy1992/mac-network-switch@0.0.3
```
then rerun this command

**Comment by harrytheedge** [comment] 2023-05-29 09:24
Hello, I was able to install the script (after having the same initial problems as @revans23). However it does not seem to work on my MBP under OS 13.3.1. I am using a 10GBE Thunderbold adapter from OWC that consistently shows up as "Thunderbolt Ethernet Slot O".

<img width="495" alt="Screenshot 2023-05-29 at 10 21 52" src="https://github.com/lxy1992/mac-network-switch/assets/771975/1479e1f8-3e25-4e34-946e-35200eec4fbe">

**Comment by harrytheedge** [comment] 2023-05-29 09:25
After plugging in the 10GBE adapter (and waiting a few seconds until it comes on), WiFi is still enabled. What to do?

**Comment by lxy1992** [comment] 2023-06-02 02:45
@harrytheedge Sorry for the late reply. It seems you are using a different hardware to connect the cable network. I will add your device type into this tool, I believe it would work at that time.

**Comment by lxy1992** [comment] 2023-06-02 02:48
@harrytheedge I will fix it today，but I don't have the device to test it. So, if it works, please let me know. I guess @revans23 ‘s problem is fixed, but I haven't received a response.

**Comment by lxy1992** [comment] 2023-06-02 05:56
@harrytheedge I already release a new version v0.0.4, which should support your cable network device. Please try it and let me know the result.

**Comment by harrytheedge** [comment] 2023-06-02 10:07
Hi @lxy1992, thank you for your help! I installed it and was able to start the service, however, wifi remains active with or without the ethernet thunderbolt adapter...
<img width="767" alt="Screenshot 2023-06-02 at 11 04 11" src="https://github.com/lxy1992/mac-network-switch/assets/771975/84fd492c-52b0-48cc-a5c6-dbb63b1f2be1">

**Comment by lxy1992** [comment] 2023-06-05 02:49
@harrytheedge Thank you for update the information, sorry for the late reply, I got covid at weekend. Let's try to figure out this problem.

First, make sure the cable network is connected. Please run the following command in your terminal, which shows all the network connections. Please show me results.

```
networksetup -listnetworkserviceorder 
```
find the info about the cable 
then, run the following command in terminal, which is used to filter the result of all network connections for finding your cable connections

```
networksetup -listnetworkserviceorder | sed -En 's/^\(Hardware Port: (.*Ethernet|USB 10.*|AX88179A.*|Thunderbolt Ethernet Slot.*), Device: (en.)\)$/\2/p'
```
this command should list 2 connections device ID, which should belong to `Thunderbolt Ethernet Slot 0` and `Thunderbolt Ethernet Slot 1`. If any of this two connections not show up, it means the problem is this command. Then we can fix it by study the name list from the first command.

If the second command is also right. Let's check the third command.
use the result of second command, it should be something like en0, en1
run the following command to check the status of network.

```
ifconfig XXX(the name from the second command, like en0)
```
it should show the information about the network, and the status of this network, if not please let me know.

Hope we can fix this ASAP, and you can enjoy this tool.

**Comment by harrytheedge** [comment] 2023-06-05 15:01
Hello @lxy1992, thank you for your continued help and support. I just tried the command and it yields this:


> (1) Thunderbolt Ethernet Slot 0
> (Hardware Port: Thunderbolt Ethernet Slot 0, Device: en12)
> 
> (2) Thunderbolt Ethernet Slot 2
> (Hardware Port: Thunderbolt Ethernet Slot 2, Device: en7)
> 
> (3) USB 10/100/1000 LAN
> (Hardware Port: USB 10/100/1000 LAN, Device: en8)
> 
> (4) Thunderbolt Bridge
> (Hardware Port: Thunderbolt Bridge, Device: bridge0)
> 
> (5) Wi-Fi
> (Hardware Port: Wi-Fi, Device: en0)
> 
> (6) USB Controls
> (Hardware Port: USB Controls, Device: usbmodem004NTGY229752)
> 
> (7) iPhone USB
> (Hardware Port: iPhone USB, Device: en9)
> 
> (8) vpn esoup
> (Hardware Port: IPSec, Device: )
> 
> (9) IOL VPN DE
> (Hardware Port: IPSec, Device: )
> 

The second command gets me this:
> en7
> en8

As "Thunderbolt Ethernet Slot 0" shows up as "en12" in the first command, there seems to be something off?

**Comment by lxy1992** [comment] 2023-06-07 02:19
@harrytheedge It seems we have found the problem, the Thunderbolt Ethernet Slot 0 is the device you use for cable network, but it doesn't show in the second command, which means it's status will not be check when the network changed. As a result of it, the auto switch will not work. Now, the problem is why, why it missed from the second command, its difficult to fix it without a problem device, but I will try today.

**Comment by lxy1992** [comment] 2023-06-07 02:28
@harrytheedge I just release a new version v0.0.5, please try it and let me know, or you can run the following command, if it shows three results, then the new version should work.

```
networksetup -listnetworkserviceorder | sed -En 's/^\(Hardware Port: (.*Ethernet|USB 10.*|AX88179A.*|Thunderbolt Ethernet Slot.*|Thunderbolt Ethernet Slot 0), Device: (en.)\)$/\2/p'
```

**Comment by harrytheedge** [comment] 2023-06-07 12:16
Hello @lxy1992, thank you! Unfortunately, the service runs, but apparently has no effect. The result of 

> networksetup -listnetworkserviceorder | sed -En 's/^\(Hardware Port: (.*Ethernet|USB 10.*|AX88179A.*|Thunderbolt Ethernet Slot.*|Thunderbolt Ethernet Slot 0), Device: (en.)\)$/\2/p'

yields:

> en7
> en8

So only 2 devices...!

**Comment by lxy1992** [comment] 2023-06-08 02:49
> This is it! Now it works!! Thank you so much!!

You are welcome. This issue I will close for now. If it's convenient, would you like to give a star to this project? thanks a lot.

**Comment by harrytheedge** [comment] 2023-08-15 10:46
Hi @lxy1992, your code has been working fantastically for me – thanks again! 

However... a few days ago, it started switching on and off for no apparent reason. 

It would all of a sudden say: "No wired network detected. Switching to Wifi" or so. The trouble is, there was no apparent disconnection from the wired network. I am using a Ubiquiti DM Pro as a router/switch. Everything runs smoothly. While I cannot rule out some LAN issue, it seems unlikely. 

Maybe the code checks too often for the presence of LAN connection? In any case, it happend now twice that a Zoom conference was disrupted because of the tool switching from LAN to WiFi. 

How do I uninstall please? Or do you have another suggestion?

Thanks!

**Comment by lxy1992** [comment] 2023-08-18 05:58
Hi, @harrytheedge 
Sorry for the late reply.

The reason why the network switch so frequently I cannot be very sure, because the devices of me or my friends or colleagues run this tool very well. 

## SelfTest Method and Reason
However, I think I could offer some suggestions based on your condition and the fundamental mechanism of this tool.
I guess the problem is from the network hardware in your local cable network or your device, like cable or the socket of this cable may have some hardware connection issues, which cause the cable connection switch between connect and disconnect frequently. I have this hypothesis is based on the following reasons, if you are interested in the mechanisms you can read it, otherwise you can only read the suggestion
> This tool will not check the connection actively, so the problem will not because the checking frequency. The base mechanism is when the network changed, there is a system network config file will change, the tool has a trigger of this change, so when the network condition changed, the tool will receive a signal, then run a check, it will check all network connections, list all of them, and find the active one, then do the logic. 

## Suggestion
we can have some tests to rule out the network condition out of the reason. 
- You can find an new place, home or company, use an new cable to connect an new network. It will rule out the network condition and hardware of the network.
- In the current network condition, change to an new device to run this tool. It can rule out the hardware issue from your device.

Finally, if the cause of this problem cannot be found by these methods. I suggest you to stop using this tool. By run the stop command I write in the Readme file in this project.

Looking forward your reply.

**Comment by harrytheedge** [comment] 2023-09-14 09:48
Hello, thank you for your extensive and kind answer. I have been in touch with the maker of my Thunderbolt-Ethernet bridge. In trying to follow their suggestions I have deleted the previous network settings so to force the Mac to create new ones. Now mac-network-switch doesn't work any more. I tried to reinstall, there was no feedback to the command "go install github.com/lxy1992/mac-network-switch@latest", but an auto-login for the service was added (again). Also, starting the service via "sudo mac-network-switch toggleAirport --switch start" worked (start was acknowledged). However, it does not switch any more, the WiFi stays on. 

I include a Dropbox link with screenshots of the Network configuration details, maybe this is helpful?

Thank you in advance!

Screenshots: https://www.dropbox.com/scl/fo/qej9ga4fiasfvd0z0k7aq/h?rlkey=zyt4lza70fxg70i4yxb8yzffq&dl=0

**Comment by lxy1992** [comment] 2023-10-03 12:56
> Hello, thank you for your extensive and kind answer. I have been in touch with the maker of my Thunderbolt-Ethernet bridge. In trying to follow their suggestions I have deleted the previous network settings so to force the Mac to create new ones. Now mac-network-switch doesn't work any more. I tried to reinstall, there was no feedback to the command "go install github.com/lxy1992/mac-network-switch@latest", but an auto-login for the service was added (again). Also, starting the service via "sudo mac-network-switch toggleAirport --switch start" worked (start was acknowledged). However, it does not switch any more, the WiFi stays on.
> 
> I include a Dropbox link with screenshots of the Network configuration details, maybe this is helpful?
> 
> Thank you in advance!
> 
> Screenshots: https://www.dropbox.com/scl/fo/qej9ga4fiasfvd0z0k7aq/h?rlkey=zyt4lza70fxg70i4yxb8yzffq&dl=0

Sorry for the late reply, I got a heavy flu last week. I see your device is Thunderbolt Ethernet OWC, I add your device type in the version 0.0.7, you can update to de version 0.0.7 to test it.

**Comment by lxy1992** [comment] 2024-04-10 03:06
Have no relay for a long time, I am going to close this issue

**Closed by lxy1992** 2024-04-10 03:06 UTC
